
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: guan1314
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false  #数据库主键自增长
    show-sql: true

logging:
  level:
    root: info
    com.guanzh: debug
  file: logs/blog-pro.log
